image: maven:3.9-eclipse-temurin-26

stages:
  - build
  - test
before_script:
  - cd "tut-project"
  
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean compile

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
