image: maven:3.9-eclipse-temurin-21

stages:
  - build
  - test
before_script:
  - cd "tut-project"
  
build-job:
  stage: build
  tags: 
    - shared-docker-runner
  script:
    - mvn clean compile

test-job:
  stage: test
  tags: 
    - shared-docker-runner
  script:
    - mvn test
